#ifndef QTCLOUDSERVICES_GLOBAL_H
#define QTCLOUDSERVICES_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QTCLOUDSERVICES_LIB
# define QTCLOUDSERVICES_EXPORT Q_DECL_EXPORT
#else
# define QTCLOUDSERVICES_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCLOUDSERVICES_GLOBAL_H
